# Generated by Django 3.2 on 2022-08-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220802_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='mucket',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
