# Generated by Django 3.2 on 2022-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220809_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='friend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.CharField(default='', max_length=100),
        ),
    ]
