# Generated by Django 3.2 on 2022-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220810_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='waiting',
        ),
        migrations.AddField(
            model_name='user',
            name='atmosphere',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='user',
            name='taste',
            field=models.FloatField(default=0.5),
        ),
    ]
