# Generated by Django 3.2 on 2022-08-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220819_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star_rating',
            field=models.FloatField(default=0),
        ),
    ]
