# Generated by Django 3.2 on 2022-08-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='star_rating',
        ),
    ]
