# Generated by Django 3.2 on 2022-08-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
