# Generated by Django 3.2 on 2022-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220810_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='atmosphere',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='review',
            name='taste',
            field=models.FloatField(default=0.5),
        ),
    ]
