# Generated by Django 3.2 on 2022-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220815_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
