# Generated by Django 3.2 on 2022-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220818_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
