# Generated by Django 3.2 on 2022-08-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star_rating',
        ),
    ]
