# Generated by Django 3.2.14 on 2022-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('shared_user', models.CharField(max_length=200)),
                ('startday', models.CharField(max_length=200)),
                ('endday', models.CharField(max_length=200)),
                ('courese_contetns', models.CharField(max_length=1000)),
            ],
        ),
    ]
