# Generated by Django 3.2 on 2022-08-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courese_contetns',
            new_name='course_contents',
        ),
        migrations.AlterField(
            model_name='course',
            name='shared_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
