# Generated by Django 3.2 on 2022-08-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220805_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='endday',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='shared_user',
            new_name='share_user',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='startday',
            new_name='start_day',
        ),
    ]
