# Generated by Django 3.2 on 2022-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220810_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.CharField(default='', max_length=200),
        ),
    ]
