# Generated by Django 4.0.5 on 2022-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=1000)),
                ('signiture', models.CharField(max_length=200)),
                ('taste', models.FloatField(default=0.0)),
                ('waiting', models.FloatField(default=0.0)),
                ('service', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('feeling', models.FloatField(default=0.0)),
            ],
        ),
    ]
