# Generated by Django 3.2 on 2022-08-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='signiture',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='store',
            name='feeling',
        ),
    ]
