# Generated by Django 3.2 on 2022-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20220818_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='img_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='like',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='parking',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='star_rating',
            field=models.FloatField(default=0),
        ),
    ]
