# Generated by Django 3.2 on 2022-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20220818_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='schedule',
            new_name='opening_hours',
        ),
        migrations.AddField(
            model_name='store',
            name='break_time',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='day_off',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='last_order',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
