# Generated by Django 3.2 on 2022-08-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20220822_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='star_rating',
        ),
    ]
